import type { Env } from './env';
import { requireAdmin, HttpError } from './access';
import { randomId } from './security';

export async function publicPosts(env:Env){const rows=await env.DB.prepare("SELECT slug,type,title,summary,organization_id,project_id,published_at,updated_at FROM posts WHERE status='published' ORDER BY published_at DESC LIMIT 100").all();return json({posts:rows.results});}
export async function publicProjects(env:Env){const rows=await env.DB.prepare("SELECT id,slug,name,summary,status,featured,highlighted,pinned,experimental,repository_url,release_url,documentation_url,updated_at FROM projects WHERE published_at IS NOT NULL AND status!='private' ORDER BY featured DESC,highlighted DESC,updated_at DESC").all();return json({projects:rows.results});}

export async function upsertProject(request:Request,env:Env):Promise<Response>{const admin=await requireAdmin(request,env,['owner','administrator','editor','creator']);const data=await request.json<Record<string,unknown>>();const id=text(data.id,80,false)||randomId('prj');const slug=slugValue(data.slug);const name=text(data.name,180,true);const summary=text(data.summary,1000,true);const status=text(data.status,40,true);const repository=text(data.repositoryUrl,500,false);const published=Boolean(data.published);await env.DB.prepare(`INSERT INTO projects(id,slug,name,summary,status,repository_url,published_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,CASE WHEN ?7=1 THEN CURRENT_TIMESTAMP ELSE NULL END,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,name=excluded.name,summary=excluded.summary,status=excluded.status,repository_url=excluded.repository_url,published_at=CASE WHEN ?7=1 THEN COALESCE(projects.published_at,CURRENT_TIMESTAMP) ELSE NULL END,updated_at=CURRENT_TIMESTAMP`).bind(id,slug,name,summary,status,repository||null,published?1:0).run();await audit(env,admin.email,'project.upsert','project',id);return json({id,slug},200);}
export async function upsertMetric(request:Request,env:Env,projectId:string):Promise<Response>{const admin=await requireAdmin(request,env,['owner','administrator','editor','creator']);const d=await request.json<Record<string,unknown>>();const key=slugValue(d.key);const label=text(d.label,120,true);const value=text(d.value,120,true);const qualifier=text(d.qualifier,500,false);const status=text(d.status,30,true);if(!['measured','provisional','historical','target'].includes(status))throw new HttpError(400,'Invalid metric status');const id=randomId('met');await env.DB.prepare(`INSERT INTO project_metrics(id,project_id,metric_key,label,value,qualifier,status,source,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,CURRENT_TIMESTAMP) ON CONFLICT(project_id,metric_key) DO UPDATE SET label=excluded.label,value=excluded.value,qualifier=excluded.qualifier,status=excluded.status,source=excluded.source,updated_at=CURRENT_TIMESTAMP`).bind(id,projectId,key,label,value,qualifier||null,status,text(d.source,500,false)||null).run();await audit(env,admin.email,'project.metric.upsert','project',projectId);return json({key});}
export async function upsertPost(request:Request,env:Env):Promise<Response>{const admin=await requireAdmin(request,env,['owner','administrator','editor','creator']);const d=await request.json<Record<string,unknown>>();const id=text(d.id,80,false)||randomId('pst');const slug=slugValue(d.slug);const title=text(d.title,220,true);const summary=text(d.summary,1000,true);const body=text(d.bodyMarkdown,100000,true);const type=text(d.type,40,true);const published=Boolean(d.published);await env.DB.prepare(`INSERT INTO posts(id,slug,type,title,summary,body_markdown,status,published_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,CASE WHEN ?7=1 THEN 'published' ELSE 'draft' END,CASE WHEN ?7=1 THEN CURRENT_TIMESTAMP ELSE NULL END,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,type=excluded.type,title=excluded.title,summary=excluded.summary,body_markdown=excluded.body_markdown,status=excluded.status,published_at=CASE WHEN ?7=1 THEN COALESCE(posts.published_at,CURRENT_TIMESTAMP) ELSE NULL END,updated_at=CURRENT_TIMESTAMP`).bind(id,slug,type,title,summary,body,published?1:0).run();await audit(env,admin.email,'post.upsert','post',id);return json({id,slug,status:published?'published':'draft'});}
async function audit(env:Env,email:string,action:string,type:string,id:string){await env.DB.prepare("INSERT INTO audit_events(id,actor_email,actor_kind,action,entity_type,entity_id) VALUES(?1,?2,'staff',?3,?4,?5)").bind(randomId('aud'),email,action,type,id).run();}
function text(v:unknown,max:number,required:boolean){const s=typeof v==='string'?v.trim():'';if(required&&!s)throw new HttpError(400,'Missing required field');if(s.length>max)throw new HttpError(400,'Field too long');return s;}function slugValue(v:unknown){const s=text(v,120,true).toLowerCase();if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(s))throw new HttpError(400,'Invalid slug');return s;}function json(v:unknown,status=200){return new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
